name: Oily Smelly
favicon: null
layout_spectrum: 0.8806357814464718
typography_spectrum: 0.15174102410674095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9637422314845026
  lightness: 0.6674321233294904
  saturation: 0.10582537832669914
  rhythmicContrast: 0.06278343149460852
purpose: []
